services:
  bookquest-app:
    image: ghcr.io/torleifg/bookquest:latest
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgvector-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      DEFAULT_LOCALE: nb
      DEFAULT_LIMIT: 30
      RECIPROCAL_RANK_FUSION_SEMANTIC_SEARCH_WEIGHT: 0.5
      RECIPROCAL_RANK_FUSION_FULL_TEXT_SEARCH_WEIGHT: 0.5
      SCHEDULER_ENABLED: true
      SCHEDULER_INITIAL_DELAY_MILLIS: 5000
      SCHEDULER_FIXED_DELAY_MILLIS: 500
      SCHEDULER_BACKOFF_SECONDS: 60
      HARVESTING_OAI_PMH_GATEWAYS_0_ENABLED: false
      HARVESTING_OAI_PMH_GATEWAYS_0_SERVICE_URI: https://oai.aja.bs.no/mlnb
      HARVESTING_OAI_PMH_GATEWAYS_0_TTL: 5
      HARVESTING_OAI_PMH_GATEWAYS_0_MAPPER: default
      HARVESTING_OAI_PMH_GATEWAYS_0_VERB: ListRecords
      HARVESTING_OAI_PMH_GATEWAYS_0_METADATA_PREFIX: marc21
      HARVESTING_BIBBI_GATEWAYS_0_ENABLED: false
      HARVESTING_BIBBI_GATEWAYS_0_SERVICE_URI: https://bibliografisk.bs.no/v1/publications/harvest
      HARVESTING_BIBBI_GATEWAYS_0_TTL: 5
      HARVESTING_BIBBI_GATEWAYS_0_MAPPER: default
      HARVESTING_BIBBI_GATEWAYS_0_LIMIT: 100
      HARVESTING_BIBBI_GATEWAYS_0_QUERY: type:(audiobook OR book)
      HARVESTING_BOKBASEN_AUDIENCE: https://api.bokbasen.io/metadata/
      HARVESTING_BOKBASEN_CLIENT: bokbasen
      HARVESTING_BOKBASEN_GATEWAYS_0_ENABLED: false
      HARVESTING_BOKBASEN_GATEWAYS_0_SERVICE_URI: https://api.bokbasen.io/metadata/export/onix/v2
      HARVESTING_BOKBASEN_GATEWAYS_0_AFTER: 19700101090000
      HARVESTING_BOKBASEN_GATEWAYS_0_MAPPER: default
      HARVESTING_BOKBASEN_GATEWAYS_0_PAGESIZE: 100
    depends_on:
      - pgvector-db

  pgvector-db:
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password

    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: