package com.github.torleifg.semanticsearch.book.service;

import lombok.Data;
import lombok.NoArgsConstructor;

import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@Data
@NoArgsConstructor
public class MetadataDTO {
    private String externalId;
    private boolean deleted;

    private String isbn;
    private String title;
    private String publisher;

    private List<Contributor> contributors = new ArrayList<>();

    private String publishedYear;
    private String description;

    private List<Classification> about = new ArrayList<>();
    private List<Classification> genreAndForm = new ArrayList<>();

    public record Classification(String id, String source, List<LocalizedString> names) {
    }

    public record LocalizedString(String language, String text) {
    }

    private URI thumbnailUrl;

    public record Contributor(List<Role> roles, String name) {

        public enum Role {
            ABR("B04"),
            ACT("E01"),
            ADP("B05"),
            RCP(null),
            ANL(null),
            ANM(null),
            ANN(null),
            ANC(null),
            APL(null),
            APE(null),
            APP(null),
            ARC(null),
            ARR("B25"),
            ACP(null),
            ADI(null),
            ART("A07"),
            ARD(null),
            ASG(null),
            ASN(null),
            ATT(null),
            AUC(null),
            AUE(null),
            AUP(null),
            AUT("A01"),
            AQT(null),
            AFT("A19"),
            AUD(null),
            AUI("A23"),
            ATO(null),
            ANT(null),
            BND(null),
            BDD(null),
            BLW(null),
            BKA(null),
            BKD(null),
            BKP(null),
            BJD(null),
            BPD(null),
            BSL(null),
            BRL(null),
            BRD(null),
            CLL(null),
            COP(null),
            CTG(null),
            CAS(null),
            CAD(null),
            CNS(null),
            CHR(null),
            CNG(null),
            CLI(null),
            COR(null),
            COL(null),
            CLT(null),
            CLR(null),
            CMM(null),
            CWT(null),
            COM(null),
            CPL(null),
            CPT(null),
            CPE(null),
            CMP(null),
            CMT(null),
            CCP(null),
            CND(null),
            CON(null),
            CSL(null),
            CSP(null),
            COS(null),
            COT(null),
            COE(null),
            CTS(null),
            CTT(null),
            CTE(null),
            CTR(null),
            CTB(null),
            CPC(null),
            CPH(null),
            CRR(null),
            CRP(null),
            CST(null),
            COU(null),
            CRT(null),
            COV(null),
            CRE(null),
            CUR(null),
            DNC(null),
            DTC(null),
            DTM(null),
            DTE(null),
            DTO(null),
            DFD(null),
            DFT(null),
            DFE(null),
            DGC(null),
            DGG(null),
            DGS(null),
            DLN(null),
            DPC(null),
            DPT(null),
            DSR(null),
            DRT(null),
            DIS(null),
            DBP(null),
            DST(null),
            DJO(null),
            DNR(null),
            DRM(null),
            DBD(null),
            DUB(null),
            EDT("B01"),
            EDC(null),
            EDM(null),
            EDD(null),
            ELG(null),
            ELT(null),
            ENJ(null),
            ENG(null),
            EGR(null),
            ETR(null),
            EVP(null),
            EXP(null),
            FAC(null),
            FLD(null),
            FMD(null),
            FDS(null),
            FLM(null),
            FMP(null),
            FMK(null),
            FPY(null),
            FRG(null),
            FMO(null),
            FON(null),
            FND(null),
            GDV(null),
            GIS(null),
            HNR(null),
            HST(null),
            HIS(null),
            ILU(null),
            ILL("A12"),
            INS(null),
            ITR(null),
            IVE(null),
            IVR(null),
            INV(null),
            ISB(null),
            JUD(null),
            JUG(null),
            LBR(null),
            LDR(null),
            LSA(null),
            LED(null),
            LEN(null),
            LTR(null),
            LIL(null),
            LBT(null),
            LSE(null),
            LSO(null),
            LGD(null),
            LTG(null),
            LYR(null),
            MKA(null),
            MFP(null),
            MFR(null),
            MRB(null),
            MRK(null),
            MDC(null),
            MTE(null),
            MTK(null),
            MXE(null),
            MOD(null),
            MON(null),
            MCP(null),
            MUP(null),
            MSD(null),
            MUS(null),
            NRT("E03"),
            NAN(null),
            OPN(null),
            ORM(null),
            ORG(null),
            OTH("Z99"),
            OWN(null),
            PAN(null),
            PPM(null),
            PTA(null),
            PTH(null),
            PAT(null),
            PRF(null),
            PMA(null),
            PHT("A08"),
            PRT(null),
            POP(null),
            PRM(null),
            PRC(null),
            PRO(null),
            PRN(null),
            PRS(null),
            PMN(null),
            PRD(null),
            PRP(null),
            PRG(null),
            PDR(null),
            PFR(null),
            PRV(null),
            PUP(null),
            PBL(null),
            PBD(null),
            PPT(null),
            RDD(null),
            RPC(null),
            RAP(null),
            RCE(null),
            RCD(null),
            RED(null),
            RXA(null),
            REN(null),
            RPT(null),
            RPS(null),
            RTH(null),
            RTM(null),
            RES(null),
            RSP(null),
            RST(null),
            RSE(null),
            RSF(null),
            RSR(null),
            REV(null),
            RBR(null),
            SCE(null),
            SAD(null),
            AUS(null),
            SCR(null),
            SCL(null),
            SPY(null),
            SEC(null),
            SLL(null),
            STD(null),
            SGN(null),
            SNG(null),
            SWD(null),
            SDS(null),
            SDE(null),
            SPK(null),
            SFX(null),
            SPN(null),
            SGD(null),
            STM(null),
            STN(null),
            STR(null),
            STL(null),
            SHT(null),
            SRV(null),
            TCH(null),
            TAD(null),
            TCD(null),
            TLD(null),
            TLG(null),
            TLH(null),
            TLP(null),
            TAU(null),
            THS(null),
            TRC(null),
            TRL("B06"),
            TYD(null),
            TYG(null),
            UVP(null),
            VDG(null),
            VFX(null),
            VAC(null),
            WIT(null),
            WDE(null),
            WDC(null),
            WAM(null),
            WAC(null),
            WAL(null),
            WAT(null),
            WIN(null),
            WPR(null),
            WST(null),
            WTS(null);

            private final String onix;

            Role(String onix) {
                this.onix = onix;
            }

            public static Role fromOnix(String code) {
                return Arrays.stream(values())
                        .filter(role -> role.onix != null && role.onix.equals(code))
                        .findFirst()
                        .orElse(Role.OTH);
            }
        }
    }
}
